name: "Build"

on:
  workflow_call:
    inputs:
      is-development:
        description: "Whether the build is for development purposes or not"
        required: false
        default: true
        type: boolean
      is-latest:
        description: "Whether the build is for the latest tag or not"
        required: false
        default: false
        type: boolean
      is-stable:
        description: "Whether the build is for a stable release or not"
        required: false
        default: false
        type: boolean
    outputs:
      image-name:
        description: "The full image name with tag"
        value: ${{ jobs.build.outputs.image-name }}
      image-version:
        description: "The version of the image"
        value: ${{ jobs.build.outputs.image-version }}

jobs:
  build:
    outputs:
      image-name: ${{ steps.tags.outputs.tags }}
      image-version: ${{ steps.tags.outputs.version }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # NOTE: We fetch depth so that we can put the right `GIT` reference
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to the registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Compute tags
        id: tags
        # If `is-development` then suffix tag with `-dev`
        # If `is-latest` then add `latest` tag
        # If not `is-stable` then suffix `-dev` to `latest
        run: |
          version="$(git describe --tags --always --dirty --match='v[0-9]*')${{ inputs.is-development && '-dev' || '' }}"
          tags="ghcr.io/${{ github.repository }}:${version}"
          if [ "${{ inputs.is-latest }}" = "true" ]; then
            tags="$tags,ghcr.io/${{ github.repository }}:latest${{ ! inputs.is-stable && '-dev' || '' }}"
          fi
          echo "tags=$tags" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT
          keepalived_version="$(sed -n 's/^KEEPALIVED_VERSION[[:space:]]*?\?=[[:space:]]*//p' Makefile | head -n1)"
          echo "keepalived-version=$keepalived_version" >> $GITHUB_OUTPUT
      - name: Build image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          build-args: |
            APPLICATION_VERSION=${{ steps.tags.outputs.version }}
            KEEPALIVED_VERSION=${{ steps.tags.outputs.keepalived-version }}
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          cache-from: type=gha,scope=virtualip-manager
          cache-to: type=gha,mode=max,scope=virtualip-manager
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GIT_ACCESS_TOKEN }}
