name: Generate SBOM

on:
  workflow_dispatch:
    inputs:
      image-name:
        description: >-
          Docker image name to use to generate sbom from
        type: string
        required: true
      image-version:
        description: >-
          The version of the image to generate sbom from
        type: string
        required: false
        default: ""
      upload-sbom:
        description: >-
          Whether to upload the sbom to the repository
        type: boolean
        required: false
        default: false
  workflow_call:
    inputs:
      image-name:
        description: >-
          Docker image name to use to generate sbom from
        type: string
        required: true
      image-version:
        description: >-
          The version of the image to generate sbom from
        type: string
        required: false
        default: ""
      upload-sbom:
        description: >-
          Whether to upload the sbom to the repository
        type: boolean
        required: false
        default: false
  
jobs:
  generate-sbom:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'go.mod'
      - name: Login to the registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate sbom for virtualip-manager
        uses: scality/sbom@e44e161a0321c285b7437be5b8de46b18a1ecb5c # v2.1.4
        with:
          target: ${{ inputs.image-name }}
          target_type: image
          version: ${{ inputs.image-version }}
          output_dir: /tmp
          output_file: sbom.json
      - name: Upload sbom to repository
        if: inputs.upload-sbom == true
        uses: scality/sbom-upload@2de9e9b5d10e044067262b250701cca1ed1b6624 # v1.0.7
        with:
          url: ${{ vars.DEPENDENCY_TRACK_HOSTNAME }}
          api-key: ${{ secrets.DEPENDENCY_TRACK_APIKEY }}
          project-sbom: /tmp/sbom.json
          parent-project-name: ${{ github.repository }}
          parent-project-collection-logic: "NONE"
