name: "Post Merge"

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      is-development: false
      is-latest: true
      is-stable: false

  generate-sbom:
    needs: build
    # 09/07/2026: Temporarily suspended: SBOM generation and upload to Dependency-Track
    if: false
    uses: ./.github/workflows/generate-sbom.yaml
    secrets: inherit
    with:
      image-name: ${{ needs.build.outputs.image-name }}
      image-version: ${{ needs.build.outputs.image-version }}
      upload-sbom: true
