name: Promote
run-name: "Promote ${{ github.ref_name }}"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      is-development: false
      is-latest: true
      is-stable: ${{ ! contains(github.ref_name, '-') }}

  create-release:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # NOTE: We explicitly set the refs otherwise the tag
          # annotations content is not fetched
          # See: https://github.com/actions/checkout/issues/882
          ref: ${{ github.ref }}

      - name: Get the artifacts name
        uses: scality/action-artifacts@v4
        id: artifacts
        with:
          method: setup
          url: https://artifacts.scality.net
          user: ${{ secrets.ARTIFACTS_USER }}
          password: ${{ secrets.ARTIFACTS_PASSWORD }}

      - uses: softprops/action-gh-release@v3
        with:
          name: VirtualIP Manager ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          # We consider pre-releases if the tag contains a hyphen
          # e.g. v1.2.3-alpha.0
          prerelease: ${{ contains(github.ref_name, '-') }}
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
