name: E2E Tests

on:
  workflow_call:

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: 'go.mod'
      - name: Running Test e2e
        env:
          GIT_AUTH_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
        run: |
          go mod tidy
          #make test-e2e
